# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Drop < Formula
  desc "A peer-to-peer file transfer tool for your local network"
  homepage "https://github.com/arjunkomath/go-drop"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arjunkomath/go-drop/releases/download/v0.1.0/drop_0.1.0_darwin_amd64.tar.gz"
      sha256 "f58c93d4bd6caf0080fb67074b7388d1b373f75e24705afdbed72660c2ef0978"

      def install
        bin.install "drop"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arjunkomath/go-drop/releases/download/v0.1.0/drop_0.1.0_darwin_arm64.tar.gz"
      sha256 "57f4e5d743b476040b69cd3135dd65c1acff0e9725672a7bb52b2b4deb2aa56e"

      def install
        bin.install "drop"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/arjunkomath/go-drop/releases/download/v0.1.0/drop_0.1.0_linux_amd64.tar.gz"
      sha256 "392c316105bf73e26a1669387767a9115188036a9ee2f6d9b3a7ae62cb8d157d"
      def install
        bin.install "drop"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arjunkomath/go-drop/releases/download/v0.1.0/drop_0.1.0_linux_arm64.tar.gz"
      sha256 "77180a71c5267431880a7547420a1248dbf5b8635863a0d61783e2b415e538e5"
      def install
        bin.install "drop"
      end
    end
  end

  test do
    system "#{bin}/drop", "version"
  end
end
