# typed: false
# frozen_string_literal: true

# This file was generated by openinsight. DO NOT EDIT.
class Openinsight < Formula
  desc "Query your database with natural language"
  homepage "https://github.com/arjunkomath/openinsight"
  version "0.14.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/arjunkomath/openinsight/releases/download/v0.14.0/openinsight-darwin-arm64.tar.gz"
      sha256 "74742dcae87bbabc4999f0d8c51b796de1a17b0c1188706ea5e1dfb072f792cc"

      def install
        bin.install "openinsight"
      end
    end

  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arjunkomath/openinsight/releases/download/v0.14.0/openinsight-linux-arm64.tar.gz"
      sha256 "32735dc47ef47e7cc8ffee056b89a500914b245d05b54a473a0a790a86378886"

      def install
        bin.install "openinsight"
      end
    end

    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/arjunkomath/openinsight/releases/download/v0.14.0/openinsight-linux-x64.tar.gz"
      sha256 "18cee7a432413d75ec3cec2e687a6fd7e69460dbc4120c1abec02c1bd723ab8a"

      def install
        bin.install "openinsight"
      end
    end
  end

  test do
    assert_match "Usage", shell_output("#{bin}/openinsight --help")
  end
end
