# typed: false
# frozen_string_literal: true

# This file was generated by openinsight. DO NOT EDIT.
class Openinsight < Formula
  desc "Query your database with natural language"
  homepage "https://github.com/arjunkomath/openinsight"
  version "0.11.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/arjunkomath/openinsight/releases/download/v0.11.0/openinsight-darwin-arm64.tar.gz"
      sha256 "0155921bb3ba224d647a0cfab5309a94e92f2da7e123f33e05d73e8ef60938c8"

      def install
        bin.install "openinsight"
      end
    end

  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arjunkomath/openinsight/releases/download/v0.11.0/openinsight-linux-arm64.tar.gz"
      sha256 "6ce13fa8e222f1972bdffa8213bd0425c7c5a321a73ea92a48dcea3c1111efb6"

      def install
        bin.install "openinsight"
      end
    end

    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/arjunkomath/openinsight/releases/download/v0.11.0/openinsight-linux-x64.tar.gz"
      sha256 "d616f7eda648dff7120bc54d69fef09eecff3caeab05fc2aa29bacc4cf7d2fa0"

      def install
        bin.install "openinsight"
      end
    end
  end

  test do
    assert_match "Usage", shell_output("#{bin}/openinsight --help")
  end
end
