# typed: false
# frozen_string_literal: true

# This file was generated by openinsight. DO NOT EDIT.
class Openinsight < Formula
  desc "Query your database with natural language"
  homepage "https://github.com/arjunkomath/openinsight"
  version "0.16.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/arjunkomath/openinsight/releases/download/v0.16.1/openinsight-darwin-arm64.tar.gz"
      sha256 "96fb2965cc6931ccdc413f9936648b9eadd081859dfea79bfbe71acfb1d16c9a"

      def install
        bin.install "openinsight"
      end
    end

  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arjunkomath/openinsight/releases/download/v0.16.1/openinsight-linux-arm64.tar.gz"
      sha256 "5872b997ab9cfb0d0d7bebe6dd0010aabd1ba04c326b97b303c1059cd8305844"

      def install
        bin.install "openinsight"
      end
    end

    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/arjunkomath/openinsight/releases/download/v0.16.1/openinsight-linux-x64.tar.gz"
      sha256 "1714e324551cb3f62e9855c704094298e46d4d92f50d728a224294fda0136fe4"

      def install
        bin.install "openinsight"
      end
    end
  end

  test do
    assert_match "Usage", shell_output("#{bin}/openinsight --help")
  end
end
